/**
 * Fixed WhatsApp message templates. These are plain string templates, not
 * generated by a model, so the wording is stable and predictable every time.
 */

export interface PoLineForMessage {
  name: string;
  unit: string;
  ordered_qty: number | string;
  unit_price: number | string;
  ordered_amount: number | string;
}

export function buildPoWhatsAppMessage(params: {
  poNumber: string;
  branchName: string;
  vendorName: string;
  lines: PoLineForMessage[];
  total: number;
  expectedDeliveryDate: string | null;
}): string {
  const lineText = params.lines
    .map((l) => `- ${l.name}: ${l.ordered_qty} ${l.unit} x Rs.${l.unit_price} = Rs.${l.ordered_amount}`)
    .join("\n");
  return (
    `*Purchase Order: ${params.poNumber}*\n` +
    `Branch: ${params.branchName}\n` +
    `Vendor: ${params.vendorName}\n\n` +
    `Items:\n${lineText}\n\n` +
    `*Total: Rs.${params.total.toFixed(2)}*\n` +
    (params.expectedDeliveryDate ? `Expected delivery: ${params.expectedDeliveryDate}\n` : "")
  );
}

export function buildGrnWhatsAppMessage(params: {
  invoiceNumber: string | null;
  branchName: string;
  vendorName: string | null;
  poNumber: string | null;
  receivedDate: string | null;
  lines: { name: string; qty: number | string; unit: string }[];
  total: number;
}): string {
  const lineText = params.lines.map((l) => `- ${l.name}: ${l.qty} ${l.unit}`).join("\n");
  return (
    `*GRN Confirmation${params.invoiceNumber ? ` - ${params.invoiceNumber}` : ""}*\n` +
    `Branch: ${params.branchName}\n` +
    (params.vendorName ? `Vendor: ${params.vendorName}\n` : "") +
    (params.poNumber ? `Linked PO: ${params.poNumber}\n` : "") +
    (params.receivedDate ? `Received: ${params.receivedDate}\n` : "") +
    `\nItems:\n${lineText}\n\n` +
    `*Total received value: Rs.${params.total.toFixed(2)}*\n`
  );
}

/** No phone param on purpose: opens WhatsApp's own contact picker so the sender chooses the recipient. */
export function buildWaLink(message: string): string {
  return `https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`;
}
